apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatwoot-rails
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatwoot-rails
  template:
    metadata:
      labels:
        app: chatwoot-rails
    spec:
      containers:
      - name: rails
        image: wavai/chatwoot-rails
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "docker/entrypoints/rails.sh && bundle exec rails server -b 0.0.0.0"]
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: chatwoot-config
        - secretRef:
            name: chatwoot-secrets
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: chatwoot-secrets
              key: DATABASE_URL
        - name: VITE_DEV_SERVER_HOST
          value: "chatwoot-vite"
        - name: NODE_ENV
          value: "production"
        - name: RAILS_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: chatwoot-rails
spec:
  selector:
    app: chatwoot-rails
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP 