apiVersion: v1
kind: Secret
metadata:
  name: chatwoot-secrets
type: Opaque
data:
  # These will be populated from GitHub Secrets
  SECRET_KEY_BASE: "$(SECRET_KEY_BASE)"
  REDIS_PASSWORD: "$(REDIS_PASSWORD)"
  POSTGRES_PASSWORD: "$(POSTGRES_PASSWORD)"
  SMTP_PASSWORD: "$(SMTP_PASSWORD)"
  # Database credentials
  POSTGRES_USER: "" # Add your base64 encoded database user
  # Mail credentials
  SMTP_USERNAME: "" # Add your base64 encoded SMTP username
  # Add other secrets as needed 