apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatwoot-rails-staging
  annotations:
    kubernetes.io/change-cause: "Staging deployment"
    container.apparmor.security.beta.kubernetes.io/rails: runtime/default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: chatwoot-rails-staging
  template:
    metadata:
      labels:
        app: chatwoot-rails-staging
      annotations:
        timestamp: "0"
    spec:
      containers:
      - name: rails
        image: wavai/chatwoot-rails-staging:v1.0.16
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "docker/entrypoints/rails.sh && bundle exec rails server -b 0.0.0.0"]
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: chatwoot-config-staging
        - secretRef:
            name: chatwoot-secrets-staging
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: chatwoot-secrets-staging
              key: DATABASE_URL
        - name: VITE_DEV_SERVER_HOST
          value: "chatwoot-vite-staging.default.svc.cluster.local"
        - name: VITE_DEV_SERVER_PORT
          value: "3036"
        - name: VITE_RUBY_HOST
          value: "staging.cx.aloochat.ai"
        - name: VITE_RUBY_PORT
          value: "443"
        - name: VITE_RUBY_HTTPS
          value: "true"
        - name: NODE_ENV
          value: "production"
        - name: RAILS_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: chatwoot-rails-staging
spec:
  selector:
    app: chatwoot-rails-staging
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
