apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatwoot-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cx.aloochat.ai
      secretName: chatwoot-tls
  rules:
    - host: cx.aloochat.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chatwoot-rails
                port:
                  number: 3000