name: Deploy to Kubernetes

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      # - name: Build and push base image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./docker/Dockerfile
      #     push: true
      #     tags: ${{ env.DOCKER_REGISTRY }}/chatwoot-base:latest
      
      - name: Build and push Rails image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/dockerfiles/rails.Dockerfile
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/chatwoot-rails:latest
      
      - name: Build and push Vite image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/dockerfiles/vite.Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/chatwoot-vite:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Check for existing cluster
        id: check-cluster
        run: |
          if doctl kubernetes cluster list --format Name | grep -q "chatwoot-cluster"; then
            echo "cluster_exists=true" >> $GITHUB_OUTPUT
            echo "Using existing cluster..."
            doctl kubernetes cluster kubeconfig save chatwoot-cluster
          else
            echo "cluster_exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create terraform.tfvars
        run: |
          cat > terraform/terraform.tfvars << EOL
          do_token = "${{ secrets.DO_TOKEN }}"
          region = "${{ secrets.REGION }}"
          environment = "${{ secrets.ENVIRONMENT }}"
          EOL
      
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
      
      - name: Terraform Apply
        if: steps.check-cluster.outputs.cluster_exists == 'false'
        run: |
          cd terraform
          terraform apply -auto-approve
      
      - name: Configure kubectl if cluster was just created
        if: steps.check-cluster.outputs.cluster_exists == 'false'
        run: |
          echo "Waiting for cluster to be ready after Terraform apply..."
          sleep 60
          doctl kubernetes cluster kubeconfig save chatwoot-cluster
      
      - name: Update Kubernetes ConfigMap
        run: |
          kubectl apply -f k8s/configmap.yaml
      
      - name: Create Kubernetes Secrets
        run: |
          kubectl delete secret chatwoot-secrets --ignore-not-found=true
          cat > secret.yaml << EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: chatwoot-secrets
          type: Opaque
          stringData:
            DATABASE_URL: "postgresql://${{ secrets.POSTGRES_USERNAME }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:${{ secrets.POSTGRES_PORT }}/${{ secrets.POSTGRES_DATABASE }}?sslmode=require"
            POSTGRES_HOST: "${{ secrets.POSTGRES_HOST }}"
            POSTGRES_PORT: "${{ secrets.POSTGRES_PORT }}"
            POSTGRES_DATABASE: "${{ secrets.POSTGRES_DATABASE }}"
            POSTGRES_USERNAME: "${{ secrets.POSTGRES_USERNAME }}"
            POSTGRES_PASSWORD: "${{ secrets.POSTGRES_PASSWORD }}"
            REDIS_URL: "${{ secrets.REDIS_URL }}"
            REDIS_PASSWORD: "${{ secrets.REDIS_PASSWORD }}"
            REDIS_HOST: "${{ secrets.REDIS_HOST }}"
            REDIS_PORT: "${{ secrets.REDIS_PORT }}"
            SECRET_KEY_BASE: "${{ secrets.SECRET_KEY_BASE }}"
            SMTP_USERNAME: "${{ secrets.SMTP_USERNAME }}"
            SMTP_PASSWORD: "${{ secrets.SMTP_PASSWORD }}"
            DOMAIN: "${{ secrets.DOMAIN || 'cx.aloochat.ai' }}"
          EOF
          kubectl create -f secret.yaml
          rm secret.yaml
      
      - name: Deploy Chatwoot to Kubernetes in ingress-nginx namespace
        run: |
          # Set namespace
          NAMESPACE=ingress-nginx

          # Apply deployments & services
          echo "Applying deployments and services in namespace default..."
          kubectl apply -n default -f k8s/rails-deployment.yaml
          kubectl apply -n default -f k8s/vite-deployment.yaml
          kubectl apply -n default -f k8s/sidekiq-deployment.yaml
          kubectl apply -n default -f k8s/mailhog-deployment.yaml


          # Wait for all deployments to be ready
          echo "Waiting for Rails deployment..."
          kubectl rollout status deployment/chatwoot-rails -n default --timeout=300s
          
          echo "Waiting for Vite deployment..."
          kubectl rollout status deployment/chatwoot-vite -n default --timeout=300s
          
          echo "Waiting for Sidekiq deployment..."
          kubectl rollout status deployment/chatwoot-sidekiq -n default --timeout=300s
          
          echo "Waiting for Mailhog deployment..."
          kubectl rollout status deployment/chatwoot-mailhog -n default --timeout=300s

          # Final status checks
          echo "Pods status:"
          kubectl get pods -n default

          echo "Services status:"
          kubectl get svc -n default

          echo "Ingress status:"
          kubectl get ingress -n default
        